System:
  name: Mask Detection Application
  NetworkDomains:
    ND3: 
      name: Network Domain 3
      AccessDelay: 0.00000277
      Bandwidth: 10000
      subNetworkDomains: [ND1, ND2]
    ND1:
      name: Network Domain 1
      AccessDelay: 0.00000277
      Bandwidth: 10000
      subNetworkDomains: []
      ComputationalLayers: 
         computationalLayer1:
            name: Edge Layer
            number: 1
            type: PhysicalAlreadyProvisioned
            Resources: 
               resource1:
                  name: RaspPi_NeuralStick
                  totalNodes: 1
                  description: Raspberry PIs 4 Model B with Neural stick 
                  cost: 0.6
                  memorySize: 4096
                  operatingSystemDistribution: Raspbian
                  operatingSystemType: Linux
                  operatingSystemVersion: 10
                  operatingSystemImageId: ""
                  secureBoot: string
                  measuredBoot: string
                  storageSize: 64GB
                  storageType: flash
                  processors:
                     processor1:
                        name: BCM2711
                        type: Cortex-A72
                        architecture: arm64
                        computingUnits: 4
                        internalMemory: 4
                        SGXFlag: False
                  accelerators:
                      accelerator1:
                         name: Neural stick 2
                         GFLOPS: 100
                         powerDraw: 1
                         memory: 4096
                         processors:
                            processor1:
                              name: P5
                              type: Movidius Myriad X VPU
                              architecture: SHAVE
                              computingUnits: 16
                              internalMemory: 0.256
    ND2:
      name: Network Domain 2
      AccessDelay: 0.00000277
      Bandwidth: 40000
      subNetworkDomains: []
      ComputationalLayers:
        computationalLayer3:
            name: Public Cloud Layer
            number: 3
            type: Virtual
            Resources:
              resource1:
                  name: VM2
                  totalNodes: 3
                  description: g5.2xlarge 
                  cost: 1.2
                  memorySize: 32768
                  storageSize: 450
                  storageType: SSD
                  operatingSystemDistribution: Ubuntu
                  operatingSystemType: Linux
                  operatingSystemVersion: 20.04
                  operatingSystemImageId: ost://horsemem.i3m.upv.es/
                                c99bc2af-76dd-498f-ba6f-36889db66856 
                  secureBoot: False
                  measuredBoot: False
                  onSpot: False
                  processors:
                     processor1:
                        name: Xeon
                        type: SkyLake
                        architecture: amd64
                        computingUnits: 8
                        internalMemory: 64
                        SGXFlag: False
                  accelerators:
                     accelerator1:
                       name: GPUa10
                       GFLOPS: 31240
                       powerDraw: 150
                       memory: 24576
                       processors:
                         processor1:
                           name: G5
                           type: GPU
                           architecture: nvidia a10g
                           computingUnits: 1
                           internalMemory: 0.256
  Components:
        component1:
           name: blurry-faces-onnx
           executionLayer: 1
           Containers:
             container1: 
                image: registry.gitlab.polimi.it/ai-sprint/blurry-faces-onnx:tag
                memorySize: 2048
                computingUnits: 0.9
                trustedExecution: False
                networkProtection: False
                fileSystemProtection: False
                GPURequirement: False
                selectedExecutionResources: RaspPi_NeuralStick
        component2:
            name: mask-detector-onnx
            executionLayer: 3
            Containers:
                 container1:
                    image: registry.gitlab.polimi.it/ai-sprint/mask-detector-onnx:tag
                    memorySize: 4096
                    computingUnits: 0.9
                    trustedExecution: False
                    networkProtection: False
                    fileSystemProtection: False
                    GPURequirement: False
                    selectedExecutionResource:  VM2 
